import { useEffect, useState, useMemo } from 'react'
import { useWallet } from '@cosmos-kit/react'
import { assets } from 'chain-registry'
import { AssetList, Asset } from '@chain-registry/types'

import {
  Box,
  Divider,
  Grid,
  Heading,
  Text,
  Stack,
  Container,
  Link,
  Button,
  Flex,
  Icon,
  useColorMode,
  useColorModeValue,
} from '@chakra-ui/react'
import { BsFillMoonStarsFill, BsFillSunFill } from 'react-icons/bs'
import { dependencies, products } from '../config'

import { WalletStatus } from '@cosmos-kit/core'
import { Product, Dependency } from '../components'
import Head from 'next/head'
import { SigningCosmWasmClient } from '@cosmjs/cosmwasm-stargate'
import { Coin } from 'cosmwasm'

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode()
  const color = useColorModeValue('primary.500', 'primary.200')

  // const {
  //   getStargateClient,
  //   getCosmWasmClient,
  //   address,
  //   setCurrentChain,
  //   currentWallet,
  //   walletStatus
  // } = useWallet();

  // useEffect(() => {
  //   setCurrentChain(chainName);
  // }, [chainName]);

  // const color = useColorModeValue('primary.500', 'primary.200');

  // // get cw20 balance
  // const [client, setClient] = useState<SigningCosmWasmClient | null>(
  //   null
  // );

  // useEffect(() => {
  //   getCosmWasmClient().then((cosmwasmClient) => {
  //     if (!cosmwasmClient || !address) {
  //       console.error('stargateClient undefined or address undefined.');
  //       return;
  //     }
  //     setClient(cosmwasmClient);
  //   });
  // }, [address, getCosmWasmClient]);
  // const [bal, setBal] = useState<Coin | null>(null);
  // useEffect(() => {
  //   if (client && address) {
  //     client
  //       .getBalance(address, denom)
  //       .then((b) => setBal(b));
  //   }
  // }, [client, address]);

  return (
    <div className="max-w-5xl py-10 mx-auto">
      <Head>
        <title>Mesh Security Testnet</title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pb-4 text-center">
        <h1 className="mb-3 text-3xl font-extrabold sm:text-4xl md:text-5xl">
          Mesh Security
        </h1>
        <h2 className="text-xl font-bold sm:text-2xl">
          Live on&nbsp;
          <span className="text-primary">Juno + Osmosis</span>
          &nbsp;testnets
        </h2>
      </div>

      <div className="grid grid-cols-1 gap-8 my-8 sm:grid-cols-2">
        <Product
          title="Osmosis Provider"
          text="Provide cross-chain security from Osmosis Testnet to Juno Testnet validators powered by Mesh Security"
          href="/provider"
        />
        <Product
          title="Juno Consumer"
          text="Receive cross-chain security on Juno Testnet from Osmosis Testnet deleagators powered by Mesh Security"
          href="/consumer"
        />
      </div>

      <div className="grid grid-cols-1 gap-8 my-8 sm:grid-cols-2">
        <Dependency
          title="Cosmos Kit"
          text="A wallet adapter for the Cosmos ecosystem."
          href="https://github.com/cosmology-tech/cosmos-kit"
        />
        <Dependency
          title="Mesh Security"
          text="Mesh security for Cosmos app-chains."
          href="https://github.com/cosmwasm/mesh-security"
        />
      </div>
    </div>
  )
}
